import fs from 'node:fs';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../storage.js',import.meta.url),'utf8');
const {default:render}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
let saved=null;
globalThis.localStorage={getItem:()=>saved,setItem:(_,v)=>{saved=v;},removeItem:()=>{saved=null;}};
const node={dataset:{},textContent:''};
let events=[];
const run=data=>render({data,parentElement:{querySelector:()=>node},setStateValue:(k,v)=>events.push([k,v])});
run({mode:'load'});assert.equal(events[0][1].payload,'');
run({mode:'sync',enabled:true,expected:'',revision:'v1',payload:'profile'});
assert.equal(JSON.parse(saved).revision,'v1');
run({mode:'sync',enabled:true,expected:'',revision:'v2',payload:'stale'});
assert.equal(JSON.parse(saved).payload,'profile');assert.equal(events.at(-1)[1].ok,false);
run({mode:'blocked',error:'Invalid settings'});assert.equal(JSON.parse(saved).revision,'v1');
run({mode:'sync',enabled:false,expected:'v1',revision:'v1'});assert.equal(saved,null);
saved='{';node.dataset={};events=[];run({mode:'load'});assert.ok(events[0][1].error);
saved=null;localStorage.setItem=()=>{throw new Error('quota')};node.dataset={};events=[];
run({mode:'sync',enabled:true,expected:'',revision:'v3',payload:'profile'});assert.equal(events[0][1].ok,false);
console.log('Browser storage: load, save, conflict, blocked, opt-out, corruption and quota checks passed.');
